---
title: "Regression"
author: "S. Mason"
date: "10/10/2018"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE}
library(readxl)
library(dplyr)
```
```{r load data, message=FALSE, warnings=FALSE}
#Load outcomes data
outcomes <- read_excel("~/Documents/ROCIanalysis/ROCI_082718e.xlsx", sheet = "Outcomes", col_types = c("numeric", "text", "numeric", "numeric", "numeric", "text", "numeric", "numeric", "numeric", "numeric", "numeric", "date", "date", "numeric", "numeric", "date", "date",  "numeric", "date", "date", "numeric", "text", "numeric", "text", "numeric", "numeric", "date", "numeric", "numeric", "text", "numeric", "text", "text"))
#Load imaging/score data
images <- read_excel("~/Documents/ROCIanalysis/ROCI_082718e.xlsx", sheet = "Imaging", col_types = c("numeric", "text", "date", "numeric", "date", "numeric", "numeric", "numeric", "date", "text", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "text"))
```
<h3>Analysis of the subgroup that have ARDS and a CXR from MICU admit (n=119)</h3>
```{r filter data}
#Creates one dataset of outcomes and scores for ARDS patients with a CXR from MICU admit
ards_admit <- filter(images, Final_Dx %in% c("ARDS", "Sepsis/ARDS"), admit_cxr == 1) %>% select(Subject_ID, cxr_date, Quad1, Quad2, Quad3, Quad4, Total)
ards <- filter(outcomes, ARDS == 1) %>% select (Subject_ID, Male, Age, non_white, Immsupp, APACHE, SOFA, days_MV, ICU_admit, ICU_days, Hosp_admit, Hosp_days, DC_coded, hosp_death, date_death, mort28d, mort60d) %>% merge(ards_admit, by="Subject_ID")
```
```{r Logit in-hospital mortality}
hosp_mort <- glm(hosp_death ~ Male+Age+non_white+Immsupp+APACHE+Total,family=binomial(link='logit'), data=ards)
summary(hosp_mort)
```
```{r Logit 28d mortality}
one_month <- glm(mort28d ~ Male+Age+non_white+Immsupp+APACHE+Total,family=binomial(link='logit'), data=ards)
summary(one_month)
```
```{r Logit 60d mortality}
two_month <- glm(mort60d ~ Male+Age+non_white+Immsupp+APACHE+Total,family=binomial(link='logit'), data=ards)
summary(one_month)
```
```{r cox proportional hazards}
refdate <- as.Date("2018-06-01")
library(survival)
library(survminer)
#Create variables with survival (in days) and a binary indicating censored status
ards <- mutate(ards, survival = ifelse(is.na(date_death) == TRUE, as.numeric(difftime(refdate, ICU_admit, units='days')), as.numeric(difftime(date_death, ICU_admit, units='days')))) %>% mutate(censor = ifelse(is.na(date_death) == TRUE, 1, 0))
#Cox regression model
res_cox <- coxph(Surv(survival, censor) ~ Male+Age+non_white+Immsupp+APACHE+Total, data=ards)
summary(res_cox)
```
```{r Kaplan Meier}
ggsurvplot(survfit(res_cox), data=ards, ggtheme = theme_minimal())
```
```{r scatterplot}
ggplot(aes(Total, survival), data=ards) + geom_point()
```

```{r Quick code}
rm(ques)
```

